openapi: 3.0.0
info:
  title: RAG Chatbot API
  description: API for Retrieval-Augmented Generation chatbot functionality
  version: 1.0.0
paths:
  /api/v1/chat:
    post:
      summary: Send a message to the chatbot
      description: Submit a query to the RAG chatbot and receive a response based on book content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Bad request - invalid input
        '429':
          description: Rate limit exceeded
        '500':
          description: Internal server error
      security:
        - api_key: []

  /api/v1/chat/{session_id}:
    get:
      summary: Get chat session history
      description: Retrieve the conversation history for a specific session
      parameters:
        - in: path
          name: session_id
          required: true
          schema:
            type: string
          description: The session ID to retrieve
      responses:
        '200':
          description: Session history retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
        '404':
          description: Session not found
        '500':
          description: Internal server error
      security:
        - api_key: []

  /api/v1/content/index:
    post:
      summary: Index book content
      description: Upload and index book content for RAG retrieval
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContentIndexRequest'
      responses:
        '200':
          description: Content indexed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentIndexResponse'
        '400':
          description: Bad request - invalid content
        '500':
          description: Internal server error
      security:
        - api_key: []

  /api/v1/health:
    get:
      summary: Health check
      description: Check the health status of the service
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  schemas:
    ChatRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: The user's question or input
          example: "What is the main concept of this chapter?"
        selected_text:
          type: string
          description: Optional text selected by the user in the book
          example: "The main concept of this chapter is reinforcement learning..."
        session_id:
          type: string
          description: Existing session ID (optional, new session created if not provided)
          example: "sess_abc123"
        include_sources:
          type: boolean
          description: Whether to include source information in response
          default: true

    ChatResponse:
      type: object
      required:
        - query
        - answer
        - results
        - session_id
      properties:
        query:
          type: string
          description: The original user query
        answer:
          type: string
          description: The AI-generated answer
        results:
          type: array
          items:
            $ref: '#/components/schemas/QueryResult'
        session_id:
          type: string
          description: The session identifier
        metadata:
          $ref: '#/components/schemas/ResponseMetadata'

    QueryResult:
      type: object
      required:
        - chunk
        - similarity_score
        - rank
      properties:
        chunk:
          $ref: '#/components/schemas/ContentChunk'
        similarity_score:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          description: Similarity score from vector search
        rank:
          type: integer
          description: Rank position in results list

    ContentChunk:
      type: object
      required:
        - id
        - content
        - source_document
      properties:
        id:
          type: string
          description: Unique identifier for the chunk
        content:
          type: string
          description: The text content of the chunk
        source_document:
          type: string
          description: Reference to the original document
        source_section:
          type: string
          description: Section within the document
        page_number:
          type: integer
          description: Page reference if applicable
        chunk_metadata:
          type: object
          description: Additional metadata for retrieval

    Message:
      type: object
      required:
        - id
        - role
        - content
        - timestamp
      properties:
        id:
          type: string
          description: Unique identifier for the message
        role:
          type: string
          enum: [user, assistant]
          description: Who sent the message
        content:
          type: string
          description: The message text
        timestamp:
          type: string
          format: date-time
          description: When the message was created
        metadata:
          type: object
          description: Additional message metadata

    ContentIndexRequest:
      type: object
      required:
        - content
        - source_document
      properties:
        content:
          type: string
          description: The book content to index
        source_document:
          type: string
          description: Document identifier
        source_section:
          type: string
          description: Section within the document
        page_number:
          type: integer
          description: Page reference if applicable

    ContentIndexResponse:
      type: object
      required:
        - status
        - indexed_chunks
      properties:
        status:
          type: string
          enum: [success, partial, error]
          description: Indexing status
        indexed_chunks:
          type: integer
          description: Number of chunks successfully indexed
        errors:
          type: array
          items:
            type: string
            description: Error messages if any

    ResponseMetadata:
      type: object
      properties:
        query_time:
          type: number
          format: float
          description: Time taken to process the query in seconds
        total_results:
          type: integer
          description: Total number of results retrieved
        timestamp:
          type: string
          format: date-time
          description: When the response was generated
        collection_name:
          type: string
          description: Name of the vector collection used

    HealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: [healthy, degraded, unhealthy]
          description: Overall health status
        details:
          type: object
          description: Component-specific health details

  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for rate limiting and access control